# Alguns métodos de resolução de sistemas lineares

# Método iterativo de Jacobi

###### Nos casos em que a convergência é possível, pode-se resolver o sistema através de métodos iterativos utilizando os coeficientes não nulos do sistema. Neste tipo de método de solução, o problema deve ser analisado caso a caso pois precisamos mapear os coeficientes não nulos.

#### No caso do sistema $AX = B$, conseguimos decompor $A = L + D + U$, onde $L$ é a triangular inferior estrita de A, $U$ é a triangular superior estrita e $D$ é a diagonal da matriz.

#### As iterações então são da forma:
$X^{k+1} = D^{-1}(B - (L+U)X^{k})$

#### E de forma desenvolvida:
#### $x_{i}^{k+1} = \frac{1}{a_{ii}}(b_{i} - \sum_{j=1}^{i-1}a_{ij}x_{j}^{k} - \sum_{j=i+1}^{n}a_{ij}x_{j}^{k})$


In [1]:
import numpy as np
import pandas as pd

In [2]:
n = 3 ## tamanho da matriz de exemplo

In [9]:
M = np.zeros((n,n+1)) ##seta uma matriz de exemplo; a coluna neste método tem que ter dimensão n+1 para entrar a resposta
k = 50 ###numero de iterações
X = np.zeros((k, n+1)) ### matriz inferior com espacinho para o controle de linha

In [4]:
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
###preenchendo com os coeficientes e valores da matriz M
M[0][0] = 3
M[0][1] = -1
M[0][2] = -1
M[0][3] = 1
M[1][0] = 1
M[1][1] = 3
M[1][2] = 1
M[1][3] = 5
M[2][0] = 1
M[2][1] = -1
M[2][2] = 2
M[2][3] = 2


In [6]:
M_orig = M.copy()

### Algoritmo iterativo de Jacobi

In [7]:
guess = [0,0,0] ##chute inicial para os valores de x

X[0,1:n+1] = guess ###atribuição do chute inicial na matriz X 
iter_ = k

### controla as iteracoes
for k in range(iter_ -1):
    ### controla as variaveis percorridas
    for i in range(n):
        soma_i = 0
        for j in range(i):  ###o python ja indexa de [1, i). nao precisa fazer até i-1
            soma_i += M[i,j]*X[k,j+1] ##Acompanhar o indice corretamente, a primeira linha em X é pro contador
        soma_i_n =0
        for j in range(i+1,n):
            soma_i_n += M[i,j]*X[k,j+1]
        X[k+1, i+1] = (1/M[i,i])*(M[i,n] - soma_i - soma_i_n)
    X[k, 0] = k

In [8]:
X

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  0.33333333,  1.66666667,  1.        ],
       [ 2.        ,  1.22222222,  1.22222222,  1.66666667],
       [ 3.        ,  1.2962963 ,  0.7037037 ,  1.        ],
       [ 4.        ,  0.90123457,  0.90123457,  0.7037037 ],
       [ 5.        ,  0.86831276,  1.13168724,  1.        ],
       [ 6.        ,  1.04389575,  1.04389575,  1.13168724],
       [ 7.        ,  1.05852766,  0.94147234,  1.        ],
       [ 8.        ,  0.98049078,  0.98049078,  0.94147234],
       [ 9.        ,  0.97398771,  1.02601229,  1.        ],
       [10.        ,  1.00867076,  1.00867076,  1.02601229],
       [11.        ,  1.01156102,  0.98843898,  1.        ],
       [12.        ,  0.99614633,  0.99614633,  0.98843898],
       [13.        ,  0.99486177,  1.00513823,  1.        ],
       [14.        ,  1.00171274,  1.00171274,  1.00513823],
       [15.        ,  1.00228366,  0.99771634,  1.        ],
       [16.        ,  0.

### Note que o algoritmo oscila bastante até chegar na solução estável $[1, 1, 1]$





# Método iterativo de Gauss-Seidel

### Trata-se de uma modificação no método de Jacobi. Nele, fazemos:

$X^{(k+1)} = (D+L)^{-1}(B - U*X^{k})$ 

#### E de forma desenvolvida, resulta:

$x_{i}^{k+1} = (b_{i} - \sum_{j=1}^{i-1}a_{ij}x_{j}^{k+1} - \sum_{j=i+1}^{n}a_{ij}x_{j}^{k})/a_{ii}$

In [13]:
guess = [0,0,0] ##chute inicial para os valores de x

X[0,1:n+1] = guess ###atribuição do chute inicial na matriz X 
iter_ = k

### controla as iteracoes
for k in range(iter_ -1):
    ### controla as variaveis percorridas
    for i in range(n):
        soma_i = 0
        for j in range(i):  ###o python ja indexa de [1, i). nao precisa fazer até i-1
            soma_i += M[i,j]*X[k+1,j+1] ##Acompanhar o indice corretamente, a primeira linha em X é pro contador
        soma_i_n =0
        for j in range(i+1,n):
            soma_i_n += M[i,j]*X[k,j+1]
        X[k+1, i+1] = (1/M[i,i])*(M[i,n] - soma_i - soma_i_n)
    X[k,0] = k

In [14]:
X

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  0.33333333,  1.55555556,  1.61111111],
       [ 2.        ,  1.38888889,  0.66666667,  0.63888889],
       [ 3.        ,  0.76851852,  1.19753086,  1.21450617],
       [ 4.        ,  1.13734568,  0.88271605,  0.87268519],
       [ 5.        ,  0.91846708,  1.06961591,  1.07557442],
       [ 6.        ,  1.04839678,  0.95867627,  0.95513975],
       [ 7.        ,  0.97127201,  1.02452942,  1.02662871],
       [ 8.        ,  1.01705271,  0.98543953,  0.98419341],
       [ 9.        ,  0.98987765,  1.00864298,  1.00938267],
       [10.        ,  1.00600855,  0.99486959,  0.99443052],
       [11.        ,  0.99643337,  1.00304537,  1.003306  ],
       [12.        ,  1.00211712,  0.99819229,  0.99803759],
       [13.        ,  0.99874329,  1.00107304,  1.00116487],
       [14.        ,  1.00074597,  0.99936305,  0.99930854],
       [15.        ,  0.9995572 ,  1.00037809,  1.00041045],
       [16.        ,  1.

### Note que converge mais rápido que o método de Jacobi; isso ocorre porque o método de Gauss-Seidel já utiliza os valores atualizados nas variáveis anteriores a $i$.

# Coeficientes de relaxação

### Ao introduzir coeficientes de relaxação no método iterativo de Gauss-Seidel, conseguimos garantir a convergência de soluções que poderiam não convergir, ao mesmo tempo em que reduzimos as oscilações entre as iterações:

$x_{i}^{k+1} = (1-\lambda)x_{i}^{k} + \lambda(b_{i} - \sum_{j=1}^{i-1}a_{ij}x_{j}^{k+1} - \sum_{j=i+1}^{n}a_{ij}x_{j}^{k})/a_{ii}$

In [15]:
guess = [0,0,0] ##chute inicial para os valores de x

X[0,1:n+1] = guess ###atribuição do chute inicial na matriz X 
iter_ = k
lambda_ = 0.5

### controla as iteracoes
for k in range(iter_ -1):
    ### controla as variaveis percorridas
    for i in range(n):
        soma_i = 0
        for j in range(i):  ###o python ja indexa de [1, i). nao precisa fazer até i-1
            soma_i += M[i,j]*X[k+1,j+1] ##Acompanhar o indice corretamente, a primeira linha em X é pro contador
        soma_i_n =0
        for j in range(i+1,n):
            soma_i_n += M[i,j]*X[k,j+1]
        X[k+1, i+1] = (1-lambda_)*X[k,i+1] + lambda_*(1/M[i,i])*(M[i,n] - soma_i - soma_i_n)
    X[k,0] = k

In [16]:
X

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  0.16666667,  0.80555556,  0.65972222],
       [ 2.        ,  0.49421296,  1.04378858,  0.96725502],
       [ 3.        ,  0.74894708,  1.06919394,  1.06368922],
       [ 4.        ,  0.89662073,  1.04121198,  1.06799242],
       [ 5.        ,  0.9665111 ,  1.0148554 ,  1.04608229],
       [ 6.        ,  0.99341183,  1.00084535,  1.02489952],
       [ 7.        ,  1.00099673,  0.99610663,  1.01122724],
       [ 8.        ,  1.00172068,  0.99589533,  1.00415728],
       [ 9.        ,  1.00086911,  0.99710993,  1.00113885],
       [10.        ,  1.00014268,  0.99834138,  1.0001191 ],
       [11.        ,  0.99981475,  0.99918171,  0.99990129],
       [12.        ,  0.99975454,  0.99964822,  0.99992406],
       [13.        ,  0.99980599,  0.9998691 ,  0.99997781],
       [14.        ,  0.99987748,  0.99995867,  1.0000092 ],
       [15.        ,  0.99993338,  0.9999889 ,  1.00001848],
       [16.        ,  0.

In [ ]:
# Converge bem mais rápido para a solução

### Note que os coeficientes que acompanham as incógnitas $x_i$ andam até o limite (i) nas colunas; ex: na linha 1, 0 passos; na linha 2, 1 passo (até L[1,0]); na linha 3, 2 passos (até L[2,1]). 

In [ ]:
c = np.zeros((n,1)) ##vetor que vai receber a resposta

In [ ]:
### começamos com i = 0; andamos de cima pra baixo na matriz
c[0] = L[0,n]/L[0,0]

In [ ]:
for i in range(1, n): ###restringimos os casos a partir de 1, pois i = 0 ja foi calculado
    termo_ind = L[i,n]/L[i,i] ###termo independente da equacao
    soma = 0
    for j in range(i):           ###esta parte do loop é a mais crucial de ser entendida; escreva numa folhinha de papel o que ela faz que fica facil de enxergar
        soma += ((L[i,j])/(L[i,i]))*c[j]
    c[i] = termo_ind - soma          ####o vetor de respostas vai sendo alimentado do começo ao fim

In [ ]:
c

### Agora vamos resolver o problema $L^{t}X = C$

### Como $L^{t}$ é triangular superior, conseguimos aproveitar o algoritmo de retrossubstituições sucessivas:

In [ ]:
x = np.zeros((n, 1)) ##vetor que vai receber a solução do sistema 

In [ ]:
Lt[:,n] = c.reshape(1,-1) ###atribuindo o valor de C na última coluna de L^t

In [ ]:
## começamos com o caso de i = n (andamos de baixo pra cima na matriz)
x[n-1] = Lt[n-1, n]/Lt[n-1, n-1]

In [ ]:
for i in range(1, n): ###restringimos os casos a partir de n-1. o indexador do python ja fa isso naturalmente [1,n) ==[1,n-1]
    termo_ind = Lt[n-i-1,n]/Lt[n-i-1,n-i-1] 
    soma = 0
    for j in range(n-i, n):           ###esta parte do loop é a mais crucial de ser entendida; escreva numa folhinha de papel o que ela faz que fica facil de enxergar
        soma += ((Lt[n-i-1,j])/(Lt[n-i-1,n-i-1]))*x[j]
    x[n-i-1] = termo_ind - soma          ####o vetor de respostas vai sendo alimentado de tras pra frente tambem

In [ ]:
x

In [ ]:
pd.DataFrame(np.dot(M_orig[:,0:n],x).round(3)) #Sim! Deu certo. 

# Agrupando tudo em funções

In [ ]:
def decomposicao_cholesky(M, n):
    L = np.zeros((M.shape))
    Lt = np.zeros((M.shape))
    
    L[0,0] = np.sqrt(M[0,0])
    L[:,0] = M[:,0]/L[0,0]

    for k in range(1,n):
        ###diagonal principal
        sum_k = 0
        for r in range(k):
            sum_k+=L[k,r]**2
        L[k,k] = np.sqrt(M[k, k] - sum_k)
    
        for i in range(k+1, n):
            sum_i = 0
            for r in range(k-1):
                sum_i += L[i,r]*L[r,k]
            L[i,k] = (1/L[k,k])*(M[i,k] - sum_i)
    Lt[0:n,0:n] = L[0:n,0:n].T
    L[:,n] = M[:,n]
    return [M, L, Lt]

In [ ]:
sols = decomposicao_cholesky(M,n)
sols

In [ ]:
def solucao(L, n):
    c = np.zeros((n, 1))
    c[0] = L[0,n]/L[0,0]
    for i in range(1, n): ###restringimos os casos a partir de 1, pois i = 0 ja foi calculado
        termo_ind = L[i,n]/L[i,i] ###termo independente da equacao
        soma = 0
        for j in range(i):           ###esta parte do loop é a mais crucial de ser entendida; escreva numa folhinha de papel o que ela faz que fica facil de enxergar
            soma += ((L[i,j])/(L[i,i]))*c[j]
        c[i] = termo_ind - soma        ####o vetor de respostas vai sendo alimentado do começo ao fim
    return c
    

In [ ]:
c = solucao(sols[1], n)

In [ ]:
def retro_solucao(U, n, c):
    x = np.zeros((n, 1))
    U[:,n] = c.reshape(1, -1)
    
    x[n-1] = U[n-1, n]/U[n-1, n-1] ## começamos com o caso de i = n (andamos de baixo pra cima na matriz)
    
    for i in range(1, n): ###restringimos os casos a partir de n-1. o indexador do python ja fa isso naturalmente [1,n) ==[1,n-1]
        termo_ind = U[n-i-1,n]/U[n-i-1,n-i-1] 
        soma = 0
        for j in range(n-i, n):           ###esta parte do loop é a mais crucial de ser entendida; escreva numa folhinha de papel o que ela faz que fica facil de enxergar
            soma += ((U[n-i-1,j])/(U[n-i-1,n-i-1]))*x[j]
        x[n-i-1] = termo_ind - soma          ####o vetor de respostas vai sendo alimentado de tras pra frente tambem
    return x

In [ ]:
X = retro_solucao(sols[2], n, c)

In [ ]:
c

In [ ]:
X

### Testando se funcionou:

In [ ]:
np.dot(M[:,0:n], X).round(3)  ##sim deu certo!